// countries.tsx
import React from 'react';

export const countries = [
 { label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/af.png" className="w-5 h-4" alt="Afghanistan" /> +93 Afghanistan</div>), value: '+93' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/al.png" className="w-5 h-4" alt="Albania" /> +355 Albania</div>), value: '+355' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/dz.png" className="w-5 h-4" alt="Algeria" /> +213 Algeria</div>), value: '+213' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/ad.png" className="w-5 h-4" alt="Andorra" /> +376 Andorra</div>), value: '+376' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/ao.png" className="w-5 h-4" alt="Angola" /> +244 Angola</div>), value: '+244' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/ag.png" className="w-5 h-4" alt="Antigua and Barbuda" /> +1 Antigua and Barbuda</div>), value: '+1' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/ar.png" className="w-5 h-4" alt="Argentina" /> +54 Argentina</div>), value: '+54' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/am.png" className="w-5 h-4" alt="Armenia" /> +374 Armenia</div>), value: '+374' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/au.png" className="w-5 h-4" alt="Australia" /> +61 Australia</div>), value: '+61' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/at.png" className="w-5 h-4" alt="Austria" /> +43 Austria</div>), value: '+43' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/az.png" className="w-5 h-4" alt="Azerbaijan" /> +994 Azerbaijan</div>), value: '+994' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/bs.png" className="w-5 h-4" alt="Bahamas" />+1 Bahamas</div>), value: '+1' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/bh.png" className="w-5 h-4" alt="Bahrain" />+973 Bahrain</div>), value: '+973' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/bd.png" className="w-5 h-4" alt="Bangladesh" />+880 Bangladesh</div>), value: '+880' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/bb.png" className="w-5 h-4" alt="Barbados" />+1 Barbados</div>), value: '+1' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/by.png" className="w-5 h-4" alt="Belarus" />+375 Belarus</div>), value: '+375' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/be.png" className="w-5 h-4" alt="Belgium" />+32 Belgium</div>), value: '+32' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/bz.png" className="w-5 h-4" alt="Belize" />+501 Belize</div>), value: '+501' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/bj.png" className="w-5 h-4" alt="Benin" />+229 Benin</div>), value: '+229' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/bt.png" className="w-5 h-4" alt="Bhutan" />+975 Bhutan</div>), value: '+975' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/bo.png" className="w-5 h-4" alt="Bolivia" />+591 Bolivia</div>), value: '+591' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/ba.png" className="w-5 h-4" alt="Bosnia and Herzegovina" />+387 Bosnia and Herzegovina</div>), value: '+387' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/bw.png" className="w-5 h-4" alt="Botswana" />+267 Botswana</div>), value: '+267' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/br.png" className="w-5 h-4" alt="Brazil" />+55 Brazil</div>), value: '+55' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/bn.png" className="w-5 h-4" alt="Brunei" />+673 Brunei</div>), value: '+673' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/bg.png" className="w-5 h-4" alt="Bulgaria" />+359 Bulgaria</div>), value: '+359' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/bf.png" className="w-5 h-4" alt="Burkina Faso" />+226 Burkina Faso</div>), value: '+226' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/bi.png" className="w-5 h-4" alt="Burundi" />+257 Burundi</div>), value: '+257' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/cv.png" className="w-5 h-4" alt="Cabo Verde" />+238 Cabo Verde</div>), value: '+238' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/kh.png" className="w-5 h-4" alt="Cambodia" />+855 Cambodia</div>), value: '+855' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/cm.png" className="w-5 h-4" alt="Cameroon" />+237 Cameroon</div>), value: '+237' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/ca.png" className="w-5 h-4" alt="Canada" />+1 Canada</div>), value: '+1' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/cf.png" className="w-5 h-4" alt="Central African Republic" />+236 Central African Republic</div>), value: '+236' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/td.png" className="w-5 h-4" alt="Chad" />+235 Chad</div>), value: '+235' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/cl.png" className="w-5 h-4" alt="Chile" />+56 Chile</div>), value: '+56' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/cn.png" className="w-5 h-4" alt="China" />+86 China</div>), value: '+86' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/co.png" className="w-5 h-4" alt="Colombia" />+57 Colombia</div>), value: '+57' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/km.png" className="w-5 h-4" alt="Comoros" />+269 Comoros</div>), value: '+269' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/cg.png" className="w-5 h-4" alt="Congo (Congo-Brazzaville)" />+242 Congo (Brazzaville)</div>), value: '+242' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/cr.png" className="w-5 h-4" alt="Costa Rica" />+506 Costa Rica</div>), value: '+506' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/ci.png" className="w-5 h-4" alt="Côte d'Ivoire" />+225 Côte d'Ivoire</div>), value: '+225' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/hr.png" className="w-5 h-4" alt="Croatia" />+385 Croatia</div>), value: '+385' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/cu.png" className="w-5 h-4" alt="Cuba" />+53 Cuba</div>), value: '+53' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/cy.png" className="w-5 h-4" alt="Cyprus" />+357 Cyprus</div>), value: '+357' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/cz.png" className="w-5 h-4" alt="Czechia (Czech Republic)" />+420 Czechia</div>), value: '+420' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/cd.png" className="w-5 h-4" alt="Democratic Republic of the Congo" />+243 Democratic Republic of the Congo</div>), value: '+243' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/dk.png" className="w-5 h-4" alt="Denmark" />+45 Denmark</div>), value: '+45' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/dj.png" className="w-5 h-4" alt="Djibouti" />+253 Djibouti</div>), value: '+253' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/dm.png" className="w-5 h-4" alt="Dominica" />+1 Dominica</div>), value: '+1' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/do.png" className="w-5 h-4" alt="Dominican Republic" />+1 Dominican Republic</div>), value: '+1' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/ec.png" className="w-5 h-4" alt="Ecuador" />+593 Ecuador</div>), value: '+593' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/eg.png" className="w-5 h-4" alt="Egypt" />+20 Egypt</div>), value: '+20' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/sv.png" className="w-5 h-4" alt="El Salvador" />+503 El Salvador</div>), value: '+503' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/gq.png" className="w-5 h-4" alt="Equatorial Guinea" />+240 Equatorial Guinea</div>), value: '+240' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/er.png" className="w-5 h-4" alt="Eritrea" />+291 Eritrea</div>), value: '+291' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/ee.png" className="w-5 h-4" alt="Estonia" />+372 Estonia</div>), value: '+372' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/sz.png" className="w-5 h-4" alt="Eswatini" />+268 Eswatini</div>), value: '+268' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/et.png" className="w-5 h-4" alt="Ethiopia" />+251 Ethiopia</div>), value: '+251' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/fj.png" className="w-5 h-4" alt="Fiji" />+679 Fiji</div>), value: '+679' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/fi.png" className="w-5 h-4" alt="Finland" />+358 Finland</div>), value: '+358' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/fr.png" className="w-5 h-4" alt="France" />+33 France</div>), value: '+33' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/ga.png" className="w-5 h-4" alt="Gabon" />+241 Gabon</div>), value: '+241' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/gm.png" className="w-5 h-4" alt="Gambia" />+220 Gambia</div>), value: '+220' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/ge.png" className="w-5 h-4" alt="Georgia" />+995 Georgia</div>), value: '+995' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/de.png" className="w-5 h-4" alt="Germany" />+49 Germany</div>), value: '+49' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/gh.png" className="w-5 h-4" alt="Ghana" />+233 Ghana</div>), value: '+233' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/gr.png" className="w-5 h-4" alt="Greece" />+30 Greece</div>), value: '+30' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/gd.png" className="w-5 h-4" alt="Grenada" />+1 Grenada</div>), value: '+1' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/gt.png" className="w-5 h-4" alt="Guatemala" />+502 Guatemala</div>), value: '+502' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/gn.png" className="w-5 h-4" alt="Guinea" />+224 Guinea</div>), value: '+224' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/gw.png" className="w-5 h-4" alt="Guinea-Bissau" />+245 Guinea-Bissau</div>), value: '+245' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/gy.png" className="w-5 h-4" alt="Guyana" />+592 Guyana</div>), value: '+592' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/ht.png" className="w-5 h-4" alt="Haiti" />+509 Haiti</div>), value: '+509' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/va.png" className="w-5 h-4" alt="Holy See" />+379 Holy See</div>), value: '+379' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/hn.png" className="w-5 h-4" alt="Honduras" />+504 Honduras</div>), value: '+504' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/hu.png" className="w-5 h-4" alt="Hungary" />+36 Hungary</div>), value: '+36' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/is.png" className="w-5 h-4" alt="Iceland" />+354 Iceland</div>), value: '+354' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/in.png" className="w-5 h-4" alt="India" />+91 India</div>), value: '+91' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/id.png" className="w-5 h-4" alt="Indonesia" />+62 Indonesia</div>), value: '+62' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/ir.png" className="w-5 h-4" alt="Iran" />+98 Iran</div>), value: '+98' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/iq.png" className="w-5 h-4" alt="Iraq" />+964 Iraq</div>), value: '+964' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/ie.png" className="w-5 h-4" alt="Ireland" />+353 Ireland</div>), value: '+353' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/il.png" className="w-5 h-4" alt="Israel" />+972 Israel</div>), value: '+972' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/it.png" className="w-5 h-4" alt="Italy" />+39 Italy</div>), value: '+39' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/jm.png" className="w-5 h-4" alt="Jamaica" />+1-876 Jamaica</div>), value: '+1876' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/jp.png" className="w-5 h-4" alt="Japan" />+81 Japan</div>), value: '+81' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/jo.png" className="w-5 h-4" alt="Jordan" />+962 Jordan</div>), value: '+962' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/kz.png" className="w-5 h-4" alt="Kazakhstan" />+7 Kazakhstan</div>), value: '+7' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/ke.png" className="w-5 h-4" alt="Kenya" />+254 Kenya</div>), value: '+254' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/ki.png" className="w-5 h-4" alt="Kiribati" />+686 Kiribati</div>), value: '+686' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/kw.png" className="w-5 h-4" alt="Kuwait" />+965 Kuwait</div>), value: '+965' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/kg.png" className="w-5 h-4" alt="Kyrgyzstan" />+996 Kyrgyzstan</div>), value: '+996' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/la.png" className="w-5 h-4" alt="Laos" />+856 Laos</div>), value: '+856' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/lv.png" className="w-5 h-4" alt="Latvia" />+371 Latvia</div>), value: '+371' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/lb.png" className="w-5 h-4" alt="Lebanon" />+961 Lebanon</div>), value: '+961' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/ls.png" className="w-5 h-4" alt="Lesotho" />+266 Lesotho</div>), value: '+266' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/lr.png" className="w-5 h-4" alt="Liberia" />+231 Liberia</div>), value: '+231' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/ly.png" className="w-5 h-4" alt="Libya" />+218 Libya</div>), value: '+218' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/li.png" className="w-5 h-4" alt="Liechtenstein" />+423 Liechtenstein</div>), value: '+423' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/lt.png" className="w-5 h-4" alt="Lithuania" />+370 Lithuania</div>), value: '+370' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/lu.png" className="w-5 h-4" alt="Luxembourg" />+352 Luxembourg</div>), value: '+352' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/mg.png" className="w-5 h-4" alt="Madagascar" />+261 Madagascar</div>), value: '+261' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/mw.png" className="w-5 h-4" alt="Malawi" />+265 Malawi</div>), value: '+265' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/my.png" className="w-5 h-4" alt="Malaysia" />+60 Malaysia</div>), value: '+60' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/mv.png" className="w-5 h-4" alt="Maldives" />+960 Maldives</div>), value: '+960' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/ml.png" className="w-5 h-4" alt="Mali" />+223 Mali</div>), value: '+223' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/mt.png" className="w-5 h-4" alt="Malta" />+356 Malta</div>), value: '+356' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/mh.png" className="w-5 h-4" alt="Marshall Islands" />+692 Marshall Islands</div>), value: '+692' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/mr.png" className="w-5 h-4" alt="Mauritania" />+222 Mauritania</div>), value: '+222' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/mu.png" className="w-5 h-4" alt="Mauritius" />+230 Mauritius</div>), value: '+230' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/mx.png" className="w-5 h-4" alt="Mexico" />+52 Mexico</div>), value: '+52' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/fm.png" className="w-5 h-4" alt="Micronesia" />+691 Micronesia</div>), value: '+691' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/md.png" className="w-5 h-4" alt="Moldova" />+373 Moldova</div>), value: '+373' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/mc.png" className="w-5 h-4" alt="Monaco" />+377 Monaco</div>), value: '+377' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/mn.png" className="w-5 h-4" alt="Mongolia" />+976 Mongolia</div>), value: '+976' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/me.png" className="w-5 h-4" alt="Montenegro" />+382 Montenegro</div>), value: '+382' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/ma.png" className="w-5 h-4" alt="Morocco" />+212 Morocco</div>), value: '+212' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/mz.png" className="w-5 h-4" alt="Mozambique" />+258 Mozambique</div>), value: '+258' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/mm.png" className="w-5 h-4" alt="Myanmar (formerly Burma)" />+95 Myanmar (formerly Burma)</div>), value: '+95' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/na.png" className="w-5 h-4" alt="Namibia" />+264 Namibia</div>), value: '+264' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/nr.png" className="w-5 h-4" alt="Nauru" />+674 Nauru</div>), value: '+674' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/np.png" className="w-5 h-4" alt="Nepal" />+977 Nepal</div>), value: '+977' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/nl.png" className="w-5 h-4" alt="Netherlands" />+31 Netherlands</div>), value: '+31' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/nz.png" className="w-5 h-4" alt="New Zealand" />+64 New Zealand</div>), value: '+64' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/ni.png" className="w-5 h-4" alt="Nicaragua" />+505 Nicaragua</div>), value: '+505' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/ne.png" className="w-5 h-4" alt="Niger" />+227 Niger</div>), value: '+227' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/ng.png" className="w-5 h-4" alt="Nigeria" />+234 Nigeria</div>), value: '+234' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/kp.png" className="w-5 h-4" alt="North Korea" />+850 North Korea</div>), value: '+850' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/mk.png" className="w-5 h-4" alt="North Macedonia" />+389 North Macedonia</div>), value: '+389' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/no.png" className="w-5 h-4" alt="Norway" />+47 Norway</div>), value: '+47' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/om.png" className="w-5 h-4" alt="Oman" />+968 Oman</div>), value: '+968' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/pk.png" className="w-5 h-4" alt="Pakistan" />+92 Pakistan</div>), value: '+92' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/pw.png" className="w-5 h-4" alt="Palau" />+680 Palau</div>), value: '+680' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/ps.png" className="w-5 h-4" alt="Palestine State" />+970 Palestine State</div>), value: '+970' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/pa.png" className="w-5 h-4" alt="Panama" />+507 Panama</div>), value: '+507' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/pg.png" className="w-5 h-4" alt="Papua New Guinea" />+675 Papua New Guinea</div>), value: '+675' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/py.png" className="w-5 h-4" alt="Paraguay" />+595 Paraguay</div>), value: '+595' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/pe.png" className="w-5 h-4" alt="Peru" />+51 Peru</div>), value: '+51' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/ph.png" className="w-5 h-4" alt="Philippines" />+63 Philippines</div>), value: '+63' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/pl.png" className="w-5 h-4" alt="Poland" />+48 Poland</div>), value: '+48' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/pt.png" className="w-5 h-4" alt="Portugal" />+351 Portugal</div>), value: '+351' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/qa.png" className="w-5 h-4" alt="Qatar" />+974 Qatar</div>), value: '+974' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/ro.png" className="w-5 h-4" alt="Romania" />+40 Romania</div>), value: '+40' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/ru.png" className="w-5 h-4" alt="Russia" />+7 Russia</div>), value: '+7' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/rw.png" className="w-5 h-4" alt="Rwanda" />+250 Rwanda</div>), value: '+250' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/kn.png" className="w-5 h-4" alt="Saint Kitts and Nevis" />+1-869 Saint Kitts and Nevis</div>), value: '+1869' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/lc.png" className="w-5 h-4" alt="Saint Lucia" />+1-758 Saint Lucia</div>), value: '+1758' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/vc.png" className="w-5 h-4" alt="Saint Vincent and the Grenadines" />+1-784 Saint Vincent and the Grenadines</div>), value: '+1784' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/ws.png" className="w-5 h-4" alt="Samoa" />+685 Samoa</div>), value: '+685' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/sm.png" className="w-5 h-4" alt="San Marino" />+378 San Marino</div>), value: '+378' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/st.png" className="w-5 h-4" alt="Sao Tome and Principe" />+239 Sao Tome and Principe</div>), value: '+239' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/sa.png" className="w-5 h-4" alt="Saudi Arabia" />+966 Saudi Arabia</div>), value: '+966' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/sn.png" className="w-5 h-4" alt="Senegal" />+221 Senegal</div>), value: '+221' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/rs.png" className="w-5 h-4" alt="Serbia" />+381 Serbia</div>), value: '+381' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/sc.png" className="w-5 h-4" alt="Seychelles" />+248 Seychelles</div>), value: '+248' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/sl.png" className="w-5 h-4" alt="Sierra Leone" />+232 Sierra Leone</div>), value: '+232' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/sg.png" className="w-5 h-4" alt="Singapore" />+65 Singapore</div>), value: '+65' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/sk.png" className="w-5 h-4" alt="Slovakia" />+421 Slovakia</div>), value: '+421' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/si.png" className="w-5 h-4" alt="Slovenia" />+386 Slovenia</div>), value: '+386' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/sb.png" className="w-5 h-4" alt="Solomon Islands" />+677 Solomon Islands</div>), value: '+677' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/so.png" className="w-5 h-4" alt="Somalia" />+252 Somalia</div>), value: '+252' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/za.png" className="w-5 h-4" alt="South Africa" />+27 South Africa</div>), value: '+27' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/kr.png" className="w-5 h-4" alt="South Korea" />+82 South Korea</div>), value: '+82' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/ss.png" className="w-5 h-4" alt="South Sudan" />+211 South Sudan</div>), value: '+211' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/es.png" className="w-5 h-4" alt="Spain" />+34 Spain</div>), value: '+34' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/lk.png" className="w-5 h-4" alt="Sri Lanka" />+94 Sri Lanka</div>), value: '+94' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/sd.png" className="w-5 h-4" alt="Sudan" />+249 Sudan</div>), value: '+249' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/sr.png" className="w-5 h-4" alt="Suriname" />+597 Suriname</div>), value: '+597' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/se.png" className="w-5 h-4" alt="Sweden" />+46 Sweden</div>), value: '+46' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/ch.png" className="w-5 h-4" alt="Switzerland" />+41 Switzerland</div>), value: '+41' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/sy.png" className="w-5 h-4" alt="Syria" />+963 Syria</div>), value: '+963' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/tj.png" className="w-5 h-4" alt="Tajikistan" />+992 Tajikistan</div>), value: '+992' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/tz.png" className="w-5 h-4" alt="Tanzania" />+255 Tanzania</div>), value: '+255' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/th.png" className="w-5 h-4" alt="Thailand" />+66 Thailand</div>), value: '+66' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/tl.png" className="w-5 h-4" alt="Timor-Leste" />+670 Timor-Leste</div>), value: '+670' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/tg.png" className="w-5 h-4" alt="Togo" />+228 Togo</div>), value: '+228' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/to.png" className="w-5 h-4" alt="Tonga" />+676 Tonga</div>), value: '+676' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/tt.png" className="w-5 h-4" alt="Trinidad and Tobago" />+1-868 Trinidad and Tobago</div>), value: '+1868' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/tn.png" className="w-5 h-4" alt="Tunisia" />+216 Tunisia</div>), value: '+216' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/tr.png" className="w-5 h-4" alt="Turkey" />+90 Turkey</div>), value: '+90' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/tm.png" className="w-5 h-4" alt="Turkmenistan" />+993 Turkmenistan</div>), value: '+993' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/tv.png" className="w-5 h-4" alt="Tuvalu" />+688 Tuvalu</div>), value: '+688' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/ug.png" className="w-5 h-4" alt="Uganda" />+256 Uganda</div>), value: '+256' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/ua.png" className="w-5 h-4" alt="Ukraine" />+380 Ukraine</div>), value: '+380' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/ae.png" className="w-5 h-4" alt="United Arab Emirates" />+971 United Arab Emirates</div>), value: '+971' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/gb.png" className="w-5 h-4" alt="United Kingdom" />+44 United Kingdom</div>), value: '+44' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/us.png" className="w-5 h-4" alt="United States" />+1 United States of America</div>), value: '+1' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/uy.png" className="w-5 h-4" alt="Uruguay" />+598 Uruguay</div>), value: '+598' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/uz.png" className="w-5 h-4" alt="Uzbekistan" />+998 Uzbekistan</div>), value: '+998' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/vu.png" className="w-5 h-4" alt="Vanuatu" />+678 Vanuatu</div>), value: '+678' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/ve.png" className="w-5 h-4" alt="Venezuela" />+58 Venezuela</div>), value: '+58' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/vn.png" className="w-5 h-4" alt="Vietnam" />+84 Vietnam</div>), value: '+84' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/ye.png" className="w-5 h-4" alt="Yemen" />+967 Yemen</div>), value: '+967' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/zm.png" className="w-5 h-4" alt="Zambia" />+260 Zambia</div>), value: '+260' },
{ label: (<div className="flex items-center gap-2"><img src="https://flagcdn.com/w40/zw.png" className="w-5 h-4" alt="Zimbabwe" />+263 Zimbabwe</div>), value: '+263' }

// ...and so on for the remaining countries


];
