// countries.tsx
import React from 'react';

export const countries = [
  { label: 'Afghanistan (+93)', value: '+93', flag: 'af' },
  { label: 'Albania (+355)', value: '+355', flag: 'al' },
  { label: 'Algeria (+213)', value: '+213', flag: 'dz' },
  { label: 'Andorra (+376)', value: '+376', flag: 'ad' },
  { label: 'Angola (+244)', value: '+244', flag: 'ao' },
  { label: 'Antigua and Barbuda (+1)', value: '+1', flag: 'ag' },
  { label: 'Argentina (+54)', value: '+54', flag: 'ar' },
  { label: 'Armenia (+374)', value: '+374', flag: 'am' },
  { label: 'Australia (+61)', value: '+61', flag: 'au' },
  { label: 'Austria (+43)', value: '+43', flag: 'at' },
  { label: 'Azerbaijan (+994)', value: '+994', flag: 'az' },
  { label: 'Bahamas (+1)', value: '+1', flag: 'bs' },
  { label: 'Bahrain (+973)', value: '+973', flag: 'bh' },
  { label: 'Bangladesh (+880)', value: '+880', flag: 'bd' },
  { label: 'Barbados (+1)', value: '+1', flag: 'bb' },
  { label: 'Belarus (+375)', value: '+375', flag: 'by' },
  { label: 'Belgium (+32)', value: '+32', flag: 'be' },
  { label: 'Belize (+501)', value: '+501', flag: 'bz' },
  { label: 'Benin (+229)', value: '+229', flag: 'bj' },
  { label: 'Bhutan (+975)', value: '+975', flag: 'bt' },
  { label: 'Bolivia (+591)', value: '+591', flag: 'bo' },
  { label: 'Bosnia and Herzegovina (+387)', value: '+387', flag: 'ba' },
  { label: 'Botswana (+267)', value: '+267', flag: 'bw' },
  { label: 'Brazil (+55)', value: '+55', flag: 'br' },
  { label: 'Brunei (+673)', value: '+673', flag: 'bn' },
  { label: 'Bulgaria (+359)', value: '+359', flag: 'bg' },
  { label: 'Burkina Faso (+226)', value: '+226', flag: 'bf' },
  { label: 'Burundi (+257)', value: '+257', flag: 'bi' },
  { label: 'Cabo Verde (+238)', value: '+238', flag: 'cv' },
  { label: 'Cambodia (+855)', value: '+855', flag: 'kh' },
  { label: 'Cameroon (+237)', value: '+237', flag: 'cm' },
  { label: 'Canada (+1)', value: '+1', flag: 'ca' },
  { label: 'Central African Republic (+236)', value: '+236', flag: 'cf' },
  { label: 'Chad (+235)', value: '+235', flag: 'td' },
  { label: 'Chile (+56)', value: '+56', flag: 'cl' },
  { label: 'China (+86)', value: '+86', flag: 'cn' },
  { label: 'Colombia (+57)', value: '+57', flag: 'co' },
  { label: 'Comoros (+269)', value: '+269', flag: 'km' },
  { label: 'Congo (Brazzaville) (+242)', value: '+242', flag: 'cg' },
  { label: 'Costa Rica (+506)', value: '+506', flag: 'cr' },
  { label: 'Côte d\'Ivoire (+225)', value: '+225', flag: 'ci' },
  { label: 'Croatia (+385)', value: '+385', flag: 'hr' },
  { label: 'Cuba (+53)', value: '+53', flag: 'cu' },
  { label: 'Cyprus (+357)', value: '+357', flag: 'cy' },
  { label: 'Czechia (+420)', value: '+420', flag: 'cz' },
  { label: 'Democratic Republic of the Congo (+243)', value: '+243', flag: 'cd' },
  { label: 'Denmark (+45)', value: '+45', flag: 'dk' },
  { label: 'Djibouti (+253)', value: '+253', flag: 'dj' },
  { label: 'Dominica (+1)', value: '+1', flag: 'dm' },
  { label: 'Dominican Republic (+1)', value: '+1', flag: 'do' },
  { label: 'Ecuador (+593)', value: '+593', flag: 'ec' },
  { label: 'Egypt (+20)', value: '+20', flag: 'eg' },
  { label: 'El Salvador (+503)', value: '+503', flag: 'sv' },
  { label: 'Equatorial Guinea (+240)', value: '+240', flag: 'gq' },
  { label: 'Eritrea (+291)', value: '+291', flag: 'er' },
  { label: 'Estonia (+372)', value: '+372', flag: 'ee' },
  { label: 'Eswatini (+268)', value: '+268', flag: 'sz' },
  { label: 'Ethiopia (+251)', value: '+251', flag: 'et' },
  { label: 'Fiji (+679)', value: '+679', flag: 'fj' },
  { label: 'Finland (+358)', value: '+358', flag: 'fi' },
  { label: 'France (+33)', value: '+33', flag: 'fr' },
  { label: 'Gabon (+241)', value: '+241', flag: 'ga' },
  { label: 'Gambia (+220)', value: '+220', flag: 'gm' },
  { label: 'Georgia (+995)', value: '+995', flag: 'ge' },
  { label: 'Germany (+49)', value: '+49', flag: 'de' },
  { label: 'Ghana (+233)', value: '+233', flag: 'gh' },
  { label: 'Greece (+30)', value: '+30', flag: 'gr' },
  { label: 'Grenada (+1)', value: '+1', flag: 'gd' },
  { label: 'Guatemala (+502)', value: '+502', flag: 'gt' },
  { label: 'Guinea (+224)', value: '+224', flag: 'gn' },
  { label: 'Guinea-Bissau (+245)', value: '+245', flag: 'gw' },
  { label: 'Guyana (+592)', value: '+592', flag: 'gy' },
  { label: 'Haiti (+509)', value: '+509', flag: 'ht' },
  { label: 'Holy See (+379)', value: '+379', flag: 'va' },
  { label: 'Honduras (+504)', value: '+504', flag: 'hn' },
  { label: 'Hungary (+36)', value: '+36', flag: 'hu' },
  { label: 'Iceland (+354)', value: '+354', flag: 'is' },
  { label: 'India (+91)', value: '+91', flag: 'in' },
  { label: 'Indonesia (+62)', value: '+62', flag: 'id' },
  { label: 'Iran (+98)', value: '+98', flag: 'ir' },
  { label: 'Iraq (+964)', value: '+964', flag: 'iq' },
  { label: 'Ireland (+353)', value: '+353', flag: 'ie' },
  { label: 'Israel (+972)', value: '+972', flag: 'il' },
  { label: 'Italy (+39)', value: '+39', flag: 'it' },
  { label: 'Jamaica (+1-876)', value: '+1876', flag: 'jm' },
  { label: 'Japan (+81)', value: '+81', flag: 'jp' },
  { label: 'Jordan (+962)', value: '+962', flag: 'jo' },
  { label: 'Kazakhstan (+7)', value: '+7', flag: 'kz' },
  { label: 'Kenya (+254)', value: '+254', flag: 'ke' },
  { label: 'Kiribati (+686)', value: '+686', flag: 'ki' },
  { label: 'Kuwait (+965)', value: '+965', flag: 'kw' },
  { label: 'Kyrgyzstan (+996)', value: '+996', flag: 'kg' },
  { label: 'Laos (+856)', value: '+856', flag: 'la' },
  { label: 'Latvia (+371)', value: '+371', flag: 'lv' },
  { label: 'Lebanon (+961)', value: '+961', flag: 'lb' },
  { label: 'Lesotho (+266)', value: '+266', flag: 'ls' },
  { label: 'Liberia (+231)', value: '+231', flag: 'lr' },
  { label: 'Libya (+218)', value: '+218', flag: 'ly' },
  { label: 'Liechtenstein (+423)', value: '+423', flag: 'li' },
  { label: 'Lithuania (+370)', value: '+370', flag: 'lt' },
  { label: 'Luxembourg (+352)', value: '+352', flag: 'lu' },
  { label: 'Madagascar (+261)', value: '+261', flag: 'mg' },
  { label: 'Malawi (+265)', value: '+265', flag: 'mw' },
  { label: 'Malaysia (+60)', value: '+60', flag: 'my' },
  { label: 'Maldives (+960)', value: '+960', flag: 'mv' },
  { label: 'Mali (+223)', value: '+223', flag: 'ml' },
  { label: 'Malta (+356)', value: '+356', flag: 'mt' },
  { label: 'Marshall Islands (+692)', value: '+692', flag: 'mh' },
  { label: 'Mauritania (+222)', value: '+222', flag: 'mr' },
  { label: 'Mauritius (+230)', value: '+230', flag: 'mu' },
  { label: 'Mexico (+52)', value: '+52', flag: 'mx' },
  { label: 'Micronesia (+691)', value: '+691', flag: 'fm' },
  { label: 'Moldova (+373)', value: '+373', flag: 'md' },
  { label: 'Monaco (+377)', value: '+377', flag: 'mc' },
  { label: 'Mongolia (+976)', value: '+976', flag: 'mn' },
  { label: 'Montenegro (+382)', value: '+382', flag: 'me' },
  { label: 'Morocco (+212)', value: '+212', flag: 'ma' },
  { label: 'Mozambique (+258)', value: '+258', flag: 'mz' },
  { label: 'Myanmar (formerly Burma) (+95)', value: '+95', flag: 'mm' },
  { label: 'Namibia (+264)', value: '+264', flag: 'na' },
  { label: 'Nauru (+674)', value: '+674', flag: 'nr' },
  { label: 'Nepal (+977)', value: '+977', flag: 'np' },
  { label: 'Netherlands (+31)', value: '+31', flag: 'nl' },
  { label: 'New Zealand (+64)', value: '+64', flag: 'nz' },
  { label: 'Nicaragua (+505)', value: '+505', flag: 'ni' },
  { label: 'Niger (+227)', value: '+227', flag: 'ne' },
  { label: 'Nigeria (+234)', value: '+234', flag: 'ng' },
  { label: 'North Korea (+850)', value: '+850', flag: 'kp' },
  { label: 'North Macedonia (+389)', value: '+389', flag: 'mk' },
  { label: 'Norway (+47)', value: '+47', flag: 'no' },
  { label: 'Oman (+968)', value: '+968', flag: 'om' },
  { label: 'Pakistan (+92)', value: '+92', flag: 'pk' },
  { label: 'Palau (+680)', value: '+680', flag: 'pw' },
  { label: 'Palestine State (+970)', value: '+970', flag: 'ps' },
  { label: 'Panama (+507)', value: '+507', flag: 'pa' },
  { label: 'Papua New Guinea (+675)', value: '+675', flag: 'pg' },
  { label: 'Paraguay (+595)', value: '+595', flag: 'py' },
  { label: 'Peru (+51)', value: '+51', flag: 'pe' },
  { label: 'Philippines (+63)', value: '+63', flag: 'ph' },
  { label: 'Poland (+48)', value: '+48', flag: 'pl' },
  { label: 'Portugal (+351)', value: '+351', flag: 'pt' },
  { label: 'Qatar (+974)', value: '+974', flag: 'qa' },
  { label: 'Romania (+40)', value: '+40', flag: 'ro' },
  { label: 'Russia (+7)', value: '+7', flag: 'ru' },
  { label: 'Rwanda (+250)', value: '+250', flag: 'rw' },
  { label: 'Saint Kitts and Nevis (+1-869)', value: '+1869', flag: 'kn' },
  { label: 'Saint Lucia (+1-758)', value: '+1758', flag: 'lc' },
  { label: 'Saint Vincent and the Grenadines (+1-784)', value: '+1784', flag: 'vc' },
  { label: 'Samoa (+685)', value: '+685', flag: 'ws' },
  { label: 'San Marino (+378)', value: '+378', flag: 'sm' },
  { label: 'Sao Tome and Principe (+239)', value: '+239', flag: 'st' },
  { label: 'Saudi Arabia (+966)', value: '+966', flag: 'sa' },
  { label: 'Senegal (+221)', value: '+221', flag: 'sn' },
  { label: 'Serbia (+381)', value: '+381', flag: 'rs' },
  { label: 'Seychelles (+248)', value: '+248', flag: 'sc' },
  { label: 'Sierra Leone (+232)', value: '+232', flag: 'sl' },
  { label: 'Singapore (+65)', value: '+65', flag: 'sg' },
  { label: 'Slovakia (+421)', value: '+421', flag: 'sk' },
  { label: 'Slovenia (+386)', value: '+386', flag: 'si' },
  { label: 'Solomon Islands (+677)', value: '+677', flag: 'sb' },
  { label: 'Somalia (+252)', value: '+252', flag: 'so' },
  { label: 'South Africa (+27)', value: '+27', flag: 'za' },
  { label: 'South Korea (+82)', value: '+82', flag: 'kr' },
  { label: 'South Sudan (+211)', value: '+211', flag: 'ss' },
  { label: 'Spain (+34)', value: '+34', flag: 'es' },
  { label: 'Sri Lanka (+94)', value: '+94', flag: 'lk' },
  { label: 'Sudan (+249)', value: '+249', flag: 'sd' },
  { label: 'Suriname (+597)', value: '+597', flag: 'sr' },
  { label: 'Sweden (+46)', value: '+46', flag: 'se' },
  { label: 'Switzerland (+41)', value: '+41', flag: 'ch' },
  { label: 'Syria (+963)', value: '+963', flag: 'sy' },
  { label: 'Tajikistan (+992)', value: '+992', flag: 'tj' },
  { label: 'Tanzania (+255)', value: '+255', flag: 'tz' },
  { label: 'Thailand (+66)', value: '+66', flag: 'th' },
  { label: 'Timor-Leste (+670)', value: '+670', flag: 'tl' },
  { label: 'Togo (+228)', value: '+228', flag: 'tg' },
  { label: 'Tonga (+676)', value: '+676', flag: 'to' },
  { label: 'Trinidad and Tobago (+1-868)', value: '+1868', flag: 'tt' },
  { label: 'Tunisia (+216)', value: '+216', flag: 'tn' },
  { label: 'Turkey (+90)', value: '+90', flag: 'tr' },
  { label: 'Turkmenistan (+993)', value: '+993', flag: 'tm' },
  { label: 'Tuvalu (+688)', value: '+688', flag: 'tv' },
  { label: 'Uganda (+256)', value: '+256', flag: 'ug' },
  { label: 'Ukraine (+380)', value: '+380', flag: 'ua' },
  { label: 'United Arab Emirates (+971)', value: '+971', flag: 'ae' },
  { label: 'United Kingdom (+44)', value: '+44', flag: 'gb' },
  { label: 'United States of America (+1)', value: '+1', flag: 'us' },
  { label: 'Uruguay (+598)', value: '+598', flag: 'uy' },
  { label: 'Uzbekistan (+998)', value: '+998', flag: 'uz' },
  { label: 'Vanuatu (+678)', value: '+678', flag: 'vu' },
  { label: 'Venezuela (+58)', value: '+58', flag: 've' },
  { label: 'Vietnam (+84)', value: '+84', flag: 'vn' },
  { label: 'Yemen (+967)', value: '+967', flag: 'ye' },
  { label: 'Zambia (+260)', value: '+260', flag: 'zm' },
  { label: 'Zimbabwe (+263)', value: '+263', flag: 'zw' }
];

// Custom option component to display flag and country name
export const CustomOption = ({ data, innerProps }: any) => (
  <div {...innerProps} className="flex items-center gap-2 py-1 px-2">
    <img 
      src={`https://flagcdn.com/w40/${data.flag}.png`} 
      className="w-5 h-4" 
      alt={data.label} 
    />
    <span>{data.label}</span>
  </div>
);

// Custom single value component
export const CustomSingleValue = ({ data }: any) => (
  <div className="flex items-center gap-2">
    <img 
      src={`https://flagcdn.com/w40/${data.flag}.png`} 
      className="w-5 h-4" 
      alt={data.label} 
    />
    <span>{data.label}</span>
  </div>
);
